server.port=8080
services.fraud=http://localhost:8081
services.payment=http://localhost:8082

resilience4j.circuitbreaker.instances.fraudService.register-health-indicator=true
resilience4j.circuitbreaker.instances.fraudService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.fraudService.sliding-window-size=5
resilience4j.circuitbreaker.instances.fraudService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.fraudService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.fraudService.wait-duration-in-open-state=10s
